### ISSUE TITLE
关于字幕组解散的截图的问题

### ISSUE THREAD

**Issue by Zzt2002** [hololiveEventCollection/hololive-20200924#1]
实际上已经有字幕组内部的人证实了这件事，具体可见bilibili“对小狐狸和狐组的一些看法”文章下的评论。
![Screenshot_20201010_004507_tv danmaku bili](https://user-images.githubusercontent.com/12124140/96369362-04e2d400-118c-11eb-826a-26c24b84300c.jpg)

**Comment by DSakura207** [comment]
建议下次发Issue的时候写一下是针对哪个文件的，这样好找一点。

我去看文章核实来源了，等一下找找应该加到哪里。

**Comment by Zzt2002** [comment]
感谢建议。在https://www.bilibili.com/read/cv7867906中下 用户 魔王小傻 的评论的回复当中

**Comment by DSakura207** [comment]
找到了。你说的是这里提到的截图吗？ https://github.com/hololiveEventCollection/hololive-20200924/blob/813e49fd0be72168321e24b0954e1b9fb4c44c3f/Extra/Fansub/README.md#L17-L25
